### ISSUE TITLE
Data Corruption Error in v0.3.3 0g-Storage-node

### ISSUE THREAD

**Issue by Josephtran102** [0glabs/0g-storage-node#110]
**Description**

I encountered a data corruption error while running the node.

⚡ root@vmi1797354 ~/0g-storage-node/run ◈ v0.3.3 ± 
```
../target/release/zgs_node --config config.toml
```
The error details are as follows:
```
thread 'tokio-runtime-worker' panicked at node/sync/src/auto_sync/tx_store.rs:103:9:
data corruption
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: sync::auto_sync::tx_store::TxStore::remove
   3: sync::service::SyncService::on_sync_msg::{{closure}}
   4: futures_util::future::future::FutureExt::poll_unpin
   5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
Error: "Panic (fatal error)"
```
***Environment:**
```
Operating System: Linux (Ubuntu 22.04.4 LTS)
Go version: go1.22.0 linux/amd64
Storage Node version: v0.3.3
```
![Screen Shot 2024-07-05 at 11 52 55](https://github.com/0glabs/0g-storage-node/assets/115780760/e436564c-4c59-474c-bbfb-de8da14211c3)
![Screen Shot 2024-07-05 at 11 54 58](https://github.com/0glabs/0g-storage-node/assets/115780760/839928e2-51de-4839-a28f-80b816033168)

**Comment by papadritta** [comment]
I have rebuilt the node and issue was sorted out, and the error’s gone.
